<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Birthday email</title>
</head>
<body>
<div class="header">
    <strong>Happy birthday, dear ${receiverName} ${receiverLastName}, </strong>
    <br>
</div>
<div class="body">
    <p>Amazing life will be your way,
        Forever, not only today.
        And let all your troubles disappear,
        And all your friends be always near!</p>
    <br>
</div>
<div>
    <p>${bye} ${name} ${lastName}<br>
    ${email} | ${phone}</p>
</div>
</body>
</html>